# Generated by Django 5.0.7 on 2024-08-02 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroDadosApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dados',
            old_name='name',
            new_name='nome',
        ),
    ]
